#!/bin/bash

# Samir's basic configuration
# Manjaro linux, xfce
# highly non-portable and system dependable

# system update
sudo pacman -Syu

# install basic stuff
# development tools
sudo pacman -S gdb \
	clang \
	clang-tools-extra \
	qemu \
	qemu-arch-extra \
	python-setuptools \
	python2-setuptools \
	python-pip \
	python2-pip \
	neovim \
	python-neovim \
	python2-neovim \
	geany \
	ctags \
	cmake \
	zsh \
	rxvt-unicode \
  help2man \
	adobe-source-code-pro-fonts \
	adobe-source-sans-pro-fonts \
	adobe-source-serif-pro-fonts 

yaourt -S global

# setup pip, python and neovim 
pip2 install --upgrade --user pip
pip install --upgrade --user pip
pip2 install --user neovim
pip install --user neovim

# add local bin to path
echo 'export PATH=$PATH:~/.local/bin' >> ~/.bashrc

# link to configuration files
mkdir -p ~/.config/nvim/colors


# get Amer files
wget http://amer.ga:1337/amer/dotfiles/raw/wip/init.vim
mv init.vim ~/.config/nvim/

# getting vim-plug to where it belongs
curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# better to do this manually
# nvim
# cd ~/.config/nvim/plugged/YouCompleteMe/
# ./install.sh --clang-completer --system-libclang

wget http://amer.ga:1337/amer/dotfiles/raw/wip/.ycm_extra_conf.py
mv .ycm_extra_conf.py ~/

# making the base16 colorschemes accualy look good in terminal and vim 
git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell


echo 'BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"' \
>> ~/.bashrc



pushd ~/.config/nvim/colors
git clone git://github.com/chriskempson/base16-vim.git base16
cp base16/colors/*.vim .
rm -rf base16
popd


mkdir ~/gitstuff
cd ~/gitstuff/
git clone https://github.com/zsh-users/antigen
git clone https://github.com/mesonbuild/meson.git

cd ~
wget http://amer.ga:1337/amer/dotfiles/raw/wip/zshrc
mv zshrc .zshrc



# ln -s `pwd`/Xresources ~/.Xresources
# ln -s `pwd`/nvimrc ~/.config/nvim/init.vim
