#!/bin/bash

# Samir's basic configuration
# Manjaro linux, xfce
# highly non-portable and system dependable

# system update
sudo pacman -Syu

# install basic stuff
# development tools
sudo pacman -S gdb clang clang-tools-extra

# editing tools
sudo pacman -S neovim python-neovim python2-neovim python-pip geany rxvt-unicode 
pip install neovim

# fonts
sudo pacman -S adobe-source-code-pro-fonts adobe-source-sans-pro-fonts adobe-source-serif-pro-fonts 

# link to configuration files
mkdir -p ~/.config/nvim/colors
ln -s ./Xresources ~/.Xresources
ln -s ./nvimrc ~/.config/nvim/init.vim

# getting vim-plug to where it belongs
curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim


# making the base16 colorschemes accualy look good in terminal and vim 
git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell

pushd ~/.config/nvim/colors
git clone git://github.com/chriskempson/base16-vim.git base16
cp base16/colors/*.vim .
rm -rf base16
popd

base16-bespin


